/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const ordermaster_Logic = require('./code/ordermaster-logic');

class order_entry_applicationSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'OrderMaster', async (request) => {
            await ordermaster_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    order_entry_applicationSrv
};